//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hrapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveEmployee
    {
        public string Emp_Type { get; set; }
        public int Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<long> Phone_Number { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_Qualification { get; set; }
        public Nullable<int> Emp_Expericence { get; set; }
        public Nullable<System.DateTime> Emp_Joining_Date { get; set; }
        public Nullable<System.DateTime> Emp_Contract_Date { get; set; }
        public Nullable<int> Emp_PF_NO { get; set; }
    }
}
